//
//  ScanPrompts.swift
//  SommLens
//
//  Created by Logan Rausch on 5/26/25.
//

enum ScanPrompts {
    static let all: [String] = [
        "Try scanning a Northern Rhône Syrah for peppery, savory vibes.",
        "Try scanning a German Riesling—zesty, often dry to off-dry.",
        "Feeling bold? Try scanning an Amarone for rich, dried-fruit depth.",
        "Scan a Crémant for elegant traditional-method bubbles—often great value.",
        "Scan a chilled Provence rosé for dry, light refreshment.",
        "Scan a Malbec from Mendoza for dark fruit and floral notes.",
        "Try scanning a Pinot Noir from Oregon—bright red fruit with earthy, savory tones.",
        "Scan a Cabernet Franc from Chinon for elegant red fruit and herbal notes.",
        "Scan a wine from Etna for mineral-driven, volcanic complexity.",
        "Scan a Barbera from Piedmont—juicy, high-acid, and food-friendly.",
        "Scan a Marlborough Sauvignon Blanc—zesty with passionfruit and green-herbal notes.",
        "Scan an orange wine for vibrant texture and intrigue.",
        "Scan a Bordeaux blend—structured, dry, and age-worthy.",
        "Scan a creamy Chardonnay from Sonoma for ripe fruit and oak influence.",
        "Scan a Beaujolais for a fruity, chillable red.",
        "Scan a Tempranillo from Rioja—structured with smooth tannins.",
        "Exploring value wines? Scan a Portuguese red from Dão.",
        "Scan a Grüner Veltliner for citrus and white pepper notes.",
        "Scan an Argentine Torrontés—highly aromatic and lively.",
        "Scan a Gamay—juicy, fresh, and fun.",
        "Scan a Syrah from Washington for bold fruit and savory spice.",
        "Scan a South African Chenin Blanc—ranging from lean and crisp to rich and textured.",
        "Scan a Nebbiolo from Barolo or Barbaresco for structure, tannin, and depth.",
        "Try scanning a Zinfandel from California—fruit-forward with spicy warmth.",
        "Scan an Austrian Zweigelt for a light, juicy, and easygoing red.",
        "Crisp and classic—scan a Sauvignon Blanc from Sancerre.",
        "Scan a rustic Corsican red for wild, herbal, Mediterranean character.",
        "Scan a Vermentino for citrus, herbs, and salty freshness.",
        "Scan a Finger Lakes Riesling—bright, high-acid, and mineral-driven.",
        "Scan an Aglianico from Basilicata—bold, structured, and brooding.",
        "Scan a Picpoul de Pinet for something crisp and seafood-friendly.",
        "Scan a Napa Valley red for bold fruit and structured intensity.",
        "Scan a Ripasso from Valpolicella for a raisin-kissed, richer twist.",
        "Scan an Albariño from Spain—zesty, saline, and coastal.",
        "Bubbles on a budget? Scan a bottle of Cava.",
        "Scan a Pinot Gris from Alsace for richness, texture, and subtle spice.",
        "Scan a Chilean Cabernet Sauvignon—structured with herbal and earthy notes.",
        "Scan a Lambrusco for a fizzy red that happily breaks the rules.",
        "Scan a wine from Santorini for intense minerality and freshness.",
        "Scan a bold Tannat from Uruguay—grippy, powerful, and intense.",
        "Scan a chilled Gamay for a perfect picnic red.",
        "Scan a Crémant de Loire for elegant bubbles with depth.",
        "Scan a Gavi from Italy for crisp green apple and citrus notes.",
        "Scan a Sicilian Frappato for light red fruit and charming freshness.",
        "Scan a white Rioja for something oaky and unexpected.",
        "Looking for freshness? Scan a Muscadet.",
        "Scan a Grenache from Spain for ripe red berry flavors.",
        "Try scanning a wine aged in amphora for an earthy, rustic feel.",
        "Scan a red blend from Paso Robles for bold, ripe richness.",
        "Scan a Vouvray for dry to off-dry Chenin Blanc.",
        "Scan an old-vine Zinfandel from California—bold and brambly.",
        "Scan a Carignan from Languedoc for rustic structure and depth.",
        "Scan a chilled Valdiguié—California’s take on Beaujolais.",
        "Scan a Marsanne–Roussanne blend from the Rhône for a waxy, floral white.",
        "Scan a bottle of Bonarda from Argentina for an inky, dark-fruited surprise.",
        "Looking for spice? Scan a Blaufränkisch from Austria.",
        "Scan a coastal Verdelho for saline freshness.",
        "Scan a Clare Valley Riesling for lime-driven, steely precision.",
        "Try scanning a Portuguese white like Arinto or Encruzado for freshness and texture.",
        "Scan a Tempranillo from Toro—riper and denser than Rioja.",
        "Scan a red from Lebanon—Château Musar if you find it.",
        "Scan a bottle from Georgia for an ancient, amphora-driven winemaking experience.",
        "Scan a dry Furmint for zesty Hungarian acidity.",
        "Scan a dessert wine—late harvest or Sauternes—for a sweet finish.",
        "Scan a Plavac Mali from Croatia—bold with rugged coastal character.",
        "Scan a bottle of Petit Verdot for deep structure and spice.",
        "Scan a Margaret River Cabernet for refined structure and minty freshness.",
        "Try scanning a Northern Italian Teroldego for dark fruit and smoky notes.",
        "Scan a Pinot Blanc from Alsace for a soft, subtly textured white.",
        "Scan a Syrah from Hawke’s Bay, New Zealand for a peppery, savory red.",
        "Scan a wine from the Jura for oxidative intrigue.",
        "Scan a red from the Canary Islands for wild, volcanic character.",
        "Scan a GSM blend from the Southern Rhône—smooth, ripe, and spicy.",
        "Scan a white from the Douro Valley—Portugal isn’t just for reds.",
        "Scan a sparkling Shiraz from Australia—it’s a wild ride.",
        "Scan a Saint-Laurent from Austria for a Pinot-like profile with extra depth.",
        "Scan a rosé of Pinot Noir to taste its elegant, refined side.",
        "Scan a Syrah from Elqui Valley, Chile for altitude-driven freshness.",
        "Scan a Pinot Noir from the Columbia Gorge—cool-climate and vibrant.",
        "Scan a red from the Bekaa Valley to explore something off the beaten path.",
        "Scan a wine from Slovenia—look for Rebula or Blaufränkisch.",
        "Scan a dry rosé from Tavel for serious structure and power.",
        "Scan a white from Lugana for creamy texture and bright citrus notes.",
        "Scan a red from the Uco Valley in Argentina—high altitude and intense flavor.",
        "Scan a wine aged in concrete for pure, clean expression.",
        "Scan a Montepulciano d’Abruzzo for a rustic, hearty red.",
        "Scan a bottle of Cannonau from Sardinia for bold fruit and aging potential.",
        "Scan a Greek white like Assyrtiko from Santorini—crisp and mineral-driven.",
        "Scan a Cabernet Sauvignon from Coonawarra for minty, eucalyptus-tinged complexity.",
        "Scan a Muscat for intensely floral aromatics and a touch of sweetness.",
        "Scan a red blend from Israel’s Galilee region—structured and surprisingly refined.",
        "Scan a Rkatsiteli for one of the world’s oldest and most historic white grapes.",
        "Scan a Canadian Riesling for racy cool-climate acidity and precision.",
        "Scan a rosé of Grenache for ripe strawberry and red berry notes.",
        "Scan an Obaideh blend from the Bekaa Valley—historic with layered texture.",
        "Scan a white Bordeaux blend for citrus-driven freshness and subtle grassy notes.",
        "Scan a Zweigelt rosé for light body and juicy berry charm.",
        "Scan a Tempranillo from Navarra—softer than Rioja yet full of character.",
        "Scan a Verdicchio from Marche for bright freshness and a classic almond finish.",
        "Scan a Négrette from Southwest France—floral, spicy, and lightly peppery."
        
    ]
}
