//
//  ScanPrompts.swift
//  SommLens
//
//  Created by Logan Rausch on 5/26/25.
//

let scanPrompts: [String] = [
    "Scan a Rhone Syrah for a spicy, earthy vibe.",
    "Scan a German Riesling—zesty and off-dry.",
    "Feeling bold? Scan an Amarone for richness and depth.",
    "Scan a Cremant for affordable bubbles and elegance.",
    "Scan a chilled Provence rose for something light and refreshing.",
    "Scan a Malbec from Mendoza to taste dark fruit and violets.",
    "Try scanning a Pinot Noir from Oregon—bright and earthy.",
    "Scan a Cabernet Franc from Chinon for herbal elegance.",
    "Scan a wine from Etna for volcanic complexity.",
    "Scan a Barbera from Piedmont—juicy and food-friendly.",
    "Scan a Marlborough Sauvignon Blanc—zesty and tropical.",
    "Scan an orange wine for vibrant, textured intrigue.",
    "Scan a Bordeaux blend—structured and dry.",
    "Scan a creamy Chardonnay from Sonoma.",
    "Scan a Beaujolais for a fruity, chillable red.",
    "Scan a Tempranillo from Rioja—structured and smooth.",
    "Explore value: scan a Portuguese red from Dao.",
    "Scan a Gruner Veltliner for pepper and citrus.",
    "Scan an Argentine Torrontes—floral and lively.",
    "Scan a Gamay—juicy, fresh, and fun.",
    "Scan a Syrah from Washington for bold fruit and spice.",
    "Scan a South African Chenin Blanc—rich or lean.",
    "Scan a Nebbiolo from Barolo or Barbaresco for structure and depth.",
    "Try scanning a Zinfandel from California—fruit-forward and spicy.",
    "Scan an Austrian Zweigelt for a light, juicy red.",
    "Crisp and classic—scan a Sauvignon Blanc from Sancerre.",
    "Scan a rustic Corsican red for something wild and herbal.",
    "Scan a Vermentino for citrus, herbs, and salty freshness.",
    "Scan a Finger Lakes Riesling—bright and mineral.",
    "Scan an Aglianico from Basilicata—bold and brooding.",
    "Scan a Picpoul de Pinet for something seafood friendly.",
    "Scan a Napa Valley red for bold, structured flavor.",
    "Scan a Ripasso from Valpolicella for a raisin-kissed twist.",
    "Scan an Albarino from Spain—zesty and coastal.",
    "Bubbles on a budget? Scan a bottle of Cava.",
    "Scan a Pinot Gris from Alsace for richness and spice.",
    "Scan a Chilean Cabernet Sauvignon—structured and earthy.",
    "Scan a Lambrusco for a fizzy red that breaks the rules.",
    "Scan a wine from Santorini for minerality and freshness.",
    "Scan a bold Tannat from Uruguay—grippy and intense.",
    "Scan a chilled Gamay for a perfect picnic red.",
    "Scan a Cremant de Loire for bubbles with depth.",
    "Scan a Gavi from Italy for crisp green apple notes.",
    "Scan a Sicilian Frappato for light red fruit and charm.",
    "Scan a white Rioja for something oaky and unexpected.",
    "Looking for freshness? Scan a Muscadet.",
    "Scan a Grenache from Spain for ripe red berries.",
    "Try scanning a wine aged in amphora for a rustic feel.",
    "Scan a red blend from Paso Robles for bold richness.",
    "Scan a Vouvray for off-dry Chenin Blanc.",
    "Scan an old-vine Zinfandel from California—bold and brambly.",
    "Scan a Carignan from Languedoc for something rustic and bold.",
    "Scan a chilled Valdiguie—California’s take on Beaujolais.",
    "Scan a Marsanne-Roussanne blend from the Rhone for a waxy, floral white.",
    "Scan a bottle of Bonarda from Argentina for an inky red surprise.",
    "Looking for spice? Scan a Blaufrankisch from Austria.",
    "Scan a coastal Verdelho for saline freshness.",
    "Scan a Clare Valley Riesling for lime and steely precision.",
    "Try scanning a Portuguese white like Arinto or Encruzado.",
    "Scan a Tempranillo from Toro—denser than Rioja.",
    "Scan a red from Lebanon—Chateau Musar if you find it.",
    "Scan a bottle from Georgia for an ancient winemaking experience.",
    "Scan a dry Furmint for zesty Hungarian acidity.",
    "Scan a dessert wine—late harvest or Sauternes—for a sweet finish.",
    "Scan a Plavac Mali from Croatia—bold with coastal character.",
    "Scan a bottle of Petit Verdot for structure and spice.",
    "Scan a Margaret River Cabernet—minty and refined.",
    "Try scanning a Northern Italian Teroldego for dark fruit and smoke.",
    "Scan a Pinot Blanc from Alsace for a soft, subtle white.",
    "Scan a Syrah from Hawke’s Bay, New Zealand for a peppery red.",
    "Scan a wine from the Jura for oxidative intrigue.",
    "Scan a red from the Canary Islands for wild volcanic flavor.",
    "Scan a GSM blend from the Southern Rhone—smooth and spicy.",
    "Scan a white from the Douro Valley—Portugal isn’t just for reds.",
    "Scan a sparkling Shiraz from Australia—it’s a wild ride.",
    "Scan a Saint-Laurent from Austria for something Pinot-like.",
    "Scan a rose of Pinot Noir and taste the elegance.",
    "Scan a Syrah from Elqui Valley, Chile for altitude freshness.",
    "Scan a Pinot Noir from the Columbia Gorge—cool and vibrant.",
    "Scan a red from the Bekaa Valley and explore something off the beaten path.",
    "Scan a wine from Slovenia—look for Rebula or Blaufrankisch.",
    "Scan a dry rose from Tavel for serious pink power.",
    "Scan a white from Lugana for creamy texture and citrus.",
    "Scan a red from the Uco Valley in Argentina—high altitude, high flavor.",
    "Scan a wine aged in concrete for pure, clean expression.",
    "Scan a Montepulciano d’Abruzzo for a rustic, hearty red.",
    "Scan a bottle of Cannonau from Sardinia for bold fruit and longevity.",
    "Scan a Greek white like Assyrtiko from Santorini—crisp and mineral.",
    "Scan a Cabernet Sauvignon from Coonawarra for minty complexity.",
    "Scan a Muscat for floral aromatics and a touch of sweetness.",
    "Scan a red blend from Israel’s Galilee region—surprisingly refined.",
    "Scan a Rkatsiteli for one of the world’s oldest white grapes.",
    "Scan a Canadian Riesling for cool-climate acidity and precision.",
    "Scan a rose of Grenache for ripe strawberry notes.",
    "Scan an Obaideh blend from the Bekaa Valley—historic and layered.",
    "Scan a white Bordeaux blend for citrus and grassy freshness.",
    "Scan a Zweigelt rose for light berry charm.",
    "Scan a Tempranillo from Navarra—softer than Rioja but just as tasty.",
    "Scan a Verdicchio from Marche for freshness and almond finish.",
    "Scan a Négrette from Southwest France—floral and peppery."
]
